# Generated by Django 3.0.3 on 2020-03-21 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='card', max_length=16)),
                ('content', models.CharField(default='card', max_length=64)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
                ('card_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='list', max_length=16)),
                ('list_id', models.CharField(max_length=32)),
                ('cards', models.ManyToManyField(related_name='card', to='boards.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_board', models.BooleanField(default=False)),
                ('name', models.CharField(default='Board', max_length=16)),
                ('board_id', models.CharField(max_length=16)),
                ('admins', models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('lists', models.ManyToManyField(to='boards.List')),
                ('members', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
