# Generated by Django 3.0.3 on 2020-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.CharField(default='NULL', max_length=16),
        ),
    ]
