# Generated by Django 3.0.3 on 2020-03-21 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_auto_20200322_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_id',
            new_name='obj_id',
        ),
        migrations.AlterField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='lists',
            field=models.ManyToManyField(blank=True, to='boards.List'),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
