# Generated by Django 3.0.3 on 2020-03-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200322_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_id',
            new_name='obj_id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='list_id',
            new_name='obj_id',
        ),
    ]
